Add jupyter-server-proxy for Tensorboard
red-hat-data-services/s2i-pytorch-notebook pull request #9
Opened 2022-07-18 23:05 UTC by VaishnaviHire

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):  https://issues.redhat.com/browse/RHODS-2978
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

2022-07-18 23:08 UTC, VaishnaviHire commented
Tested on OCP 4.10

For Notebook-controller: 

![Screen Shot 2022-07-18 at 7 00 57 PM](https://user-images.githubusercontent.com/17230536/179631599-aafd2450-ccff-45e6-9799-431a296b3ecb.png)

2022-07-19 07:22 UTC, lugi0 commented on .aicoe-ci.yaml
> +  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.3.0"
wasn't pytorch's base image the minimal CUDA one? or is this something else?

2022-07-19 07:24 UTC, lugi0 commented on Pipfile
> +tensorboard = "==2.6"
If we change the tensorboard version then the metadata of the image should be updated to reflect it in the spawner

2022-07-19 13:39 UTC, VaishnaviHire commented on .aicoe-ci.yaml
> +  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.3.0"
This update is just for the `aicoe-ci` pipeline. The base image would still be from https://github.com/red-hat-data-services/odh-deployer/blob/main/jupyterhub/cuda-11.4.2/manifests.yaml#L37.

cc: @harshad16

2022-07-19 13:40 UTC, harshad16 commented on .aicoe-ci.yaml
> +  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.3.0"
yes correct just for testing, as mentioned here as well. https://github.com/red-hat-data-services/s2i-tensorflow-gpu-notebook/pull/11#discussion_r924515915

2022-07-19 13:43 UTC, harshad16 requested changes
lgtm
just few comments

2022-07-19 13:43 UTC, harshad16 commented on .aicoe-ci.yaml
>    - thoth-precommit
can we remove this, it not very effective anymore.

2022-07-19 13:43 UTC, harshad16 commented on Pipfile
> +#jupyterlab-s3-browser = "*"
lets remove these commented one out.
it would just create confusing.

2022-07-20 13:57 UTC, harshad16 reviewed
/lgtm
thanks :100:

2022-07-21 14:23 UTC, VaishnaviHire commented
@lugi0 Live Build that includes changes in Pytorch , Tensorflow images and updated dependency versions

quay.io/modh/rhods-operator-live-catalog:1.14.0-rhods-2978

2022-07-22 15:03 UTC, lugi0 commented
Tested and working well, hold on merging until https://github.com/red-hat-data-services/ods-ci/pull/470 is merged

2022-07-25 13:59 UTC, lugi0 approved these changes
Automation is merged, this can move ahead

2022-07-26 15:46 UTC, samuelvl approved these changes

2022-07-26 15:46 UTC, merged